name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    #- uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo -V
        cargo build --release
#    - name: Build
#      run: |
#        env
#        cargo -V
#        cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
