name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Build
      run: |
        cargo install cross
        cross build --target x86_64-pc-windows-gnu
        ls -l
#    - name: Build
#      run: |
#        env
#        cargo -V
#        cargo build --verbose
#    - name: Run tests
#      run: cargo test --verbose
